apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
