apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  type: NodePort  # Service type set to NodePort
  ports:
    - name: amqp
      port: 5672          # Port exposed by the service
      targetPort: 5672    # Port on the container
      nodePort: 30500     # NodePort field corrected
    - name: management
      port: 15672         # Port exposed by the service
      targetPort: 15672   # Port on the container
      nodePort: 30501     # NodePort field corrected
