apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default  # Ensure it is created in the default namespace
spec:
  selector:
    app: zipkin        # Must match the Deployment's label
  ports:
    - protocol: TCP
      port: 9411       # Service port exposed
      targetPort: 9411 # Container's port
  type: LoadBalancer
